### ISSUE TITLE
dmrid.dat http: interface not being updated?

### ISSUE THREAD

**Issue by WA3PNY** [n7tae/xlxd#8]
The http: sourcing of DMR ID's seems not to be updating.  K1NRA was one of those who was given an ID outside the US domain by DMR-Marc.  He updated his ID to 3146839 (from 110xxxx).  He was locked out by a "unrecognized Id error" in xlxd.  I added him to the local file correctly, and changed main.h to look at the local file.  The error stopped.  His updated ID seems to not be correct in the online http source.  BTW, he is correct in updated DMRIds.dat files that have switched to Radio-ID as source.

**Comment by w1bsb** [comment]
This issue will need to be opened with the source xlxd github repo, as this is just a fork. We use the same url as the source this was forked from. This was originally forked from https://github.com/LX3JL/xlxd
